[context.production]
    command = 'hugo && cp ./_redirects ./public/_redirects'
    publish = 'public'

[build.environment]
    HUGO_VERSION = '0.122.0'

[context.link]
    command = 'hugo -c link --config link.toml'